/*
 * This source file was generated by the Gradle 'init' task
 */
package com.crackersnacker;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.*;

public class App {
    private boolean closed = false;
    private long previousTime = 0;
    public final int UPDATES_PER_SECOND = 60;
    public final int UPDATE_TIME = 1000000000 / UPDATES_PER_SECOND;

    private JFrame window;
    private Game game;

    public App() {
        this.window = createGameWindow();
        this.game = new Game(new KeyboardInput());
        window.add(game);
        window.addKeyListener(new KeyboardInput());
        window.setVisible(true);
        game.setUpObject();
    }

    private JFrame createGameWindow() {
        JFrame frame = new JFrame();
        frame.setSize(1200, 800);
        frame.setTitle("The Northern Hills");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                closed = true;
            }
        });
        return frame;
    }
    
    public void loop() {
        while (!closed) {
            if (System.nanoTime() < previousTime + UPDATE_TIME) {
                continue;
            }
            long timeDifference = System.nanoTime() - previousTime;
            previousTime = System.nanoTime();
            float deltaTime = timeDifference / 1000000F;
            game.updateObject(deltaTime);
            game.repaint();
        }
        game.cleanUpObject();
    }
}
